### ISSUE TITLE
加载不出来

### ISSUE THREAD

**Issue by vipheyue** [Zane96/GithubQuery#1]
Error:Could not GET 'https://jitpack.io/com/github/Kermit95/ExUtils/v1.0.1/ExUtils-v1.0.1.pom'. Received status code 401 from server: Repo not found or no access token provided
<a href="toggle.offline.mode">Enable Gradle 'offline mode' and sync project</a>

**Comment by Zane96** [comment]
你好，
      非常抱歉，由于我同学的这个工具库已经太久没有维护所以删掉了。我已经删除了这个库。你可以直接在你拉取的版本里面删除这个库或者再次拉取我刚push上去的代码。

**Comment by vipheyue** [comment]
可以了  不过 MyApplication 里面 JUtils.initialize(this); 这一行可以去掉。你现在大三哈。还不错尼

**Comment by Zane96** [comment]
嗯，其实也没用到。现在大二，马上大三了。哈哈

**Comment by vipheyue** [comment]
soga ,好好学，前途无量！后天来你们学校比赛

**Comment by Zane96** [comment]
你也是在重庆读书？

**Comment by vipheyue** [comment]
恩，我邮电移通的，刚毕业，你算好的，之前遇到你学长都太垃圾

**Comment by vipheyue** [comment]
没事可以一起吹牛 哈哈

**Comment by vipheyue** [comment]
我337681920 何悦 叫我一下 留你QQ也可以
